sudo: required
services:
    - docker

before_install:
    - docker build -t yasir1983:docker-ci-playground -f Dockerfile.dev .

script:
    - docker run -e CI=true yasir1983:docker-ci-playground npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react-app"
    env: "DockerReactApp-env"
    bucket_name: "elasticbeanstalk-us-east-1-207897739129"
    bucket_path: "docker-react-app"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"