sudo: required
services:
    - docker

before_install:
    - docker build -t yasir1983:docker-ci-playground -f Dockerfile.dev .

script:
    - docker run -e CI=true yasir1983:docker-ci-playground npm run test